# Generated by Django 5.0.7 on 2025-05-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_protect_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='share_with_classmates',
            field=models.BooleanField(default=True),
        ),
    ]
