# Generated by Django 5.0.7 on 2025-05-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userpreference_share_with_classmates'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='aspect_ratio_height',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='aspect_ratio_width',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='screen_fit',
            field=models.CharField(choices=[('fit', 'Fit'), ('fill', 'Fill')], default='fit', max_length=10),
        ),
    ]
