# Generated by Django 5.0.7 on 2025-06-08 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userpreference_aspect_ratio_height_and_more'),
    ]

    operations = [
        # Remove ConceptTile model - data is now stored locally
        migrations.DeleteModel(
            name='ConceptTile',
        ),
        # Remove SyncLog model - no longer needed with local file storage
        migrations.DeleteModel(
            name='SyncLog',
        ),
    ]
