# Generated by Django 5.0.7 on 2025-05-18 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_disabled', models.BooleanField(default=False)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_type', models.CharField(choices=[('linear', 'Linear'), ('quadratic', 'Quadratic'), ('cubic', 'Cubic'), ('sqrt', 'Square Root'), ('cbrt', 'Cube Root'), ('abs', 'Absolute Value'), ('rational', 'Rational/Inverse'), ('exponential', 'Exponential'), ('logarithmic', 'Logarithmic'), ('trigonometric', 'Trigonometric'), ('piecewise', 'Piecewise')], max_length=20)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=250)),
                ('height', models.IntegerField(default=200)),
                ('desmos_state', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_tiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'concept_type')},
            },
        ),
    ]
