# Generated by Django 5.0.7 on 2025-05-30 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_authcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPCode',
        ),
    ]
