# Generated by Django 5.0.7 on 2025-05-30 03:22

from django.db import migrations


def mark_existing_users_verified(apps, schema_editor):
    """Mark all existing users as email verified so they don't need to re-verify"""
    User = apps.get_model('authentication', 'User')
    User.objects.filter(is_email_verified=False).update(is_email_verified=True)


def reverse_mark_existing_users_verified(apps, schema_editor):
    """Reverse the operation - mark all users as unverified"""
    User = apps.get_model('authentication', 'User')
    User.objects.filter(is_email_verified=True).update(is_email_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_add_email_verified_field'),
    ]

    operations = [
        migrations.RunPython(
            mark_existing_users_verified,
            reverse_mark_existing_users_verified,
        ),
    ]
